// File generated by flutterfire_cli.
// Frugal AI Firebase Configuration - frugal-ai-295b9 project

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Return Android configuration by default (can be switched based on platform)
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIJ2VxzsILVUSKSXpvvR5DyEp0s8kTkzo',
    appId: '1:249527223824:android:e8f2a5c9d3b1c4f7a9e2',
    messagingSenderId: '249527223824',
    projectId: 'frugal-ai-295b9',
    storageBucket: 'frugal-ai-295b9.appspot.com',
    databaseURL: 'https://frugal-ai-295b9-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIJ2VxzsILVUSKSXpvvR5DyEp0s8kTkzo',
    appId: '1:249527223824:ios:a4b5c6d7e8f9g0h1i2j3',
    messagingSenderId: '249527223824',
    projectId: 'frugal-ai-295b9',
    storageBucket: 'frugal-ai-295b9.appspot.com',
    databaseURL: 'https://frugal-ai-295b9-default-rtdb.firebaseio.com',
    iosClientId:
        '249527223824-j57mo80u52g2u6d66akgcvbr8plvo7ec.apps.googleusercontent.com',
    iosBundleId: 'com.frugalai.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIJ2VxzsILVUSKSXpvvR5DyEp0s8kTkzo',
    appId: '1:249527223824:web:b5c6d7e8f9g0h1i2j3k4',
    messagingSenderId: '249527223824',
    projectId: 'frugal-ai-295b9',
    authDomain: 'frugal-ai-295b9.firebaseapp.com',
    storageBucket: 'frugal-ai-295b9.appspot.com',
    databaseURL: 'https://frugal-ai-295b9-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIJ2VxzsILVUSKSXpvvR5DyEp0s8kTkzo',
    appId: '1:249527223824:windows:c6d7e8f9g0h1i2j3k4l5',
    messagingSenderId: '249527223824',
    projectId: 'frugal-ai-295b9',
    authDomain: 'frugal-ai-295b9.firebaseapp.com',
    storageBucket: 'frugal-ai-295b9.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIJ2VxzsILVUSKSXpvvR5DyEp0s8kTkzo',
    appId: '1:249527223824:macos:d7e8f9g0h1i2j3k4l5m6',
    messagingSenderId: '249527223824',
    projectId: 'frugal-ai-295b9',
    storageBucket: 'frugal-ai-295b9.appspot.com',
    databaseURL: 'https://frugal-ai-295b9-default-rtdb.firebaseio.com',
    iosClientId:
        '249527223824-j57mo80u52g2u6d66akgcvbr8plvo7ec.apps.googleusercontent.com',
    iosBundleId: 'com.frugalai.app.macos',
  );
}
